import Header from "./header.tsx";
import Sidebar from "./sidebar.tsx";
import Footer from "./footer.tsx";
import PrevNext from "./prev-next.tsx";
import {
  currentEditionId,
  hasGlossary,
  titleMain,
  titleQual,
} from "./editions.ts";

// Top-level layout: <header>, then a single .layout-wrapper holding the
// sidebar / main / TOC trio, then <footer> as a sibling of the wrapper.
// The wrapper-then-footer split (rather than one body-level grid) is what
// makes sticky sidebar/TOC slide up cleanly as the footer scrolls in,
// instead of overflowing past the wrapper's bottom. The TOC's <ol> is
// empty here; a post-render processor in _config.ts walks the document
// for <emu-clause id=…> and fills it in.
//
// BASE_PATH lets the same build target both `localhost/` (empty prefix) and the
// gh-pages deploy, e.g. `kt3k.github.io/ecma262/draft/` (non-empty prefix);
// every chapter is rendered locally so there's no cross-site fallback. deployBase
// is the parent of the per-edition sites (es2024/, es2025/, …) the
// VersionSwitcher dropdown points at.
const basePath = Deno.env.get("BASE_PATH") ?? "";
const deployBase = "/ecma262";
// Social-card metadata needs ABSOLUTE urls (crawlers don't resolve relative
// og:image), so the deploy origin is baked in regardless of BASE_PATH. The
// per-edition cards live in dist/og/ (committed lume/og/, copied by
// assemble-dist; regenerate with tools/og/generate-og.mjs).
const siteOrigin = "https://kt3k.github.io";
const ogImage = `${siteOrigin}${deployBase}/og/og-${currentEditionId}.png`;
const ogDescription = `${titleMain}${
  titleQual ? ` ${titleQual}` : ""
} — The ECMAScript® Language Specification, restyled for reading.`;

export default function Page(
  { children, title, slug }: {
    children: unknown;
    title?: string;
    slug?: string;
  },
) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{title ?? "ECMA-262"}</title>
        <meta name="description" content={ogDescription} />
        <meta property="og:site_name" content="ECMA-262 Restyled" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content={title ?? "ECMA-262"} />
        <meta property="og:description" content={ogDescription} />
        <meta property="og:image" content={ogImage} />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        {slug !== undefined && (
          <meta
            property="og:url"
            content={`${siteOrigin}${basePath}${
              slug === "" || slug === "index" ? "" : `/${slug}`
            }/`}
          />
        )}
        <meta name="twitter:card" content="summary_large_image" />
        {
          /* The "JS" mark favicon — the same icon the Nextra build shipped
            (its app/icon.svg). basePath-prefixed so it resolves under a
            sub-path deploy too. */
        }
        <link
          rel="icon"
          type="image/svg+xml"
          href={`${basePath}/favicon.svg`}
        />
        {
          /* Set the theme class before any styles apply so returning visitors
            don't see a light-mode flash. Reads localStorage with a
            prefers-color-scheme fallback. The matching click handler is
            wired below after the body mounts. */
        }
        <script
          dangerouslySetInnerHTML={{
            __html:
              `(function(){var p;try{p=localStorage.getItem("theme");}catch(_){}if(p!=="light"&&p!=="dark")p="system";var r=document.documentElement;r.dataset.theme=p;if(p==="dark"||(p==="system"&&matchMedia("(prefers-color-scheme:dark)").matches))r.classList.add("dark");})();`,
          }}
        />
        {
          /* highlight.js GitHub theme — colours the <span class="hljs-*">
            tokens that build-chapters.mjs / ecmarkup emit inside spec
            <pre><code> blocks. Loaded BEFORE styles.css so the rules
            in styles.css can zero out the theme's white .hljs background
            (tc39.es parity, ecmarkup.css `pre code.hljs { background:
            0 0 }`) without specificity gymnastics. */
        }
        <link rel="stylesheet" href={`${basePath}/hljs-github.css`} />
        <link rel="stylesheet" href={`${basePath}/styles.css`} />
        {
          /* Custom search module — uses Pagefind core (pagefind.js) and
            renders its own combobox + dropdown, instead of dropping in
            Pagefind's pre-built PagefindUI bundle (which has fixed DOM
            and doesn't match Nextra's look). The pagefind/ index itself
            is still generated by `deno task pagefind`; if it's absent
            the input will sit there inert (no CDN dependency either way). */
        }
        <script type="module" src={`${basePath}/search.js`}></script>
        {
          /* xref hover-cards: lazy-loads xref-index.json (written next to the
            chapter pages by the build) on first hover and shows a definition
            card for emu-xref / dfn links. Deferred + reads the index URL off
            its own data attribute. */
        }
        <script
          defer
          src={`${basePath}/xref-hover.js`}
          data-xref-index={`${basePath}/xref-index.json`}
        >
        </script>
        {
          /* In-chapter reading progress: a header bar on mobile, a
            "section N / M" counter + read-dimming in the right-rail TOC on
            desktop. Chrome only — nothing is inserted into the prose. */
        }
        <script defer src={`${basePath}/reading-progress.js`}></script>
        {
          /* Context breadcrumb: sticky ancestor-clause chain under the
            header for deeply nested sections (hidden ≤2 levels). */
        }
        <script defer src={`${basePath}/breadcrumb.js`}></script>
        {
          /* Heading anchor links: copy the permalink to the clipboard on click
            (the "#" links work as plain anchors without it). */
        }
        <script defer src={`${basePath}/heading-anchors.js`}></script>
        {/* "Back to top" pill on long chapters. */}
        <script defer src={`${basePath}/back-to-top.js`}></script>
      </head>
      <body>
        {
          /* a11y: keyboard users can jump past the header + sidebar to land
            on the article without tabbing through every nav link first.
            Hidden visually; revealed on focus by the .skip-nav CSS. */
        }
        <a class="skip-nav" href="#content">Skip to content</a>
        <Header basePath={basePath} deployBase={deployBase} />
        {
          /* Sidebar + main + TOC live inside a single flex wrapper, footer
            sits OUTSIDE it as a sibling. That way the sidebar's and TOC's
            sticky containing block ends right above the footer, so they
            slide up out of view as the footer scrolls in (Nextra parity —
            see <div class="x:mx-auto x:flex x:max-w-(...)"> in their DOM). */
        }
        <div class="layout-wrapper">
          <Sidebar
            basePath={basePath}
            currentSlug={slug ?? ""}
            hasGlossary={hasGlossary}
          />
          {
            /* data-pagefind-body marks the indexable region for Pagefind
              (sidebar/header are ignored). Same attribute unlocks the
              ecma-spec.css spec-typography block (font-size: 1.0625rem,
              line-height: 1.65, --ecma-measure: 45rem, heading
              tracking) — without it the body falls back to the browser
              default 16px and the prose feels cramped vs the Nextra
              build, which sets the attribute via its layout. */
          }
          <main id="content" data-pagefind-body="true">
            {children}
            <PrevNext
              basePath={basePath}
              currentSlug={slug ?? ""}
            />
          </main>
          <aside class="toc" aria-label="On this page">
            {
              /* Whole-spec position strip (idea F), pinned at the top of the
                rail above "On This Page" so its position is the same on every
                page. Skeleton only — _config.ts injects the per-page position
                (data-before/-span + ticks + chapter segments) and
                reading-progress.js advances it on scroll. aria-hidden: an
                orientation aid duplicating what the chapter list already gives. */
            }
            <div id="spec-pos" class="spec-pos" aria-hidden="true">
              <span class="sp-track">
                <i class="sp-done"></i>
                <i class="sp-dot"></i>
                <span class="sp-pop"></span>
              </span>
              <span class="sp-label"></span>
            </div>
            <h2>On This Page</h2>
            <ol></ol>
            {
              /* "Question? Give us feedback →" — Nextra's default link below
                the on-this-page list. URL mirrors the format nextra-theme-docs
                generates from docsRepositoryBase: /issues/new with a
                pre-filled title + labels=feedback. */
            }
            <a
              class="toc-feedback"
              href={`https://github.com/kt3k/ecma262/issues/new?title=${
                encodeURIComponent(`Feedback for "${title ?? "ECMA-262"}"`)
              }&labels=feedback`}
              target="_blank"
              rel="noreferrer"
            >
              Question? Give us feedback
              {/* 45° external-link arrow, matches Nextra's TOC feedback icon. */}
              <svg
                class="toc-feedback-arrow"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="1.7"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
              >
                <path d="M7 17L17 7"></path>
                <path d="M7 7h10v10"></path>
              </svg>
            </a>
          </aside>
        </div>
        <Footer />
        {
          /* Theme toggle + hamburger menu click handlers. Sit at the end of
            <body> so the target elements exist when listeners attach. */
        }
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Theme switch: the trigger opens a Light / Dark / System menu
              // (Nextra's ThemeSwitch select) rather than toggling directly.
              // The chosen mode is stored under localStorage "theme" ("light"/
              // "dark"; "system" clears it) and reflected on html[data-theme],
              // which the early-paint script reads to avoid a flash. "System"
              // tracks prefers-color-scheme live.
              (function(){
                var mq=matchMedia("(prefers-color-scheme:dark)");
                var r=document.documentElement;
                function cur(){var p=localStorage.getItem("theme");return p==="light"||p==="dark"?p:"system";}
                function apply(mode){
                  r.dataset.theme=mode;
                  r.classList.toggle("dark",mode==="dark"||(mode==="system"&&mq.matches));
                  document.querySelectorAll(".theme-option").forEach(function(o){
                    o.setAttribute("aria-checked",o.dataset.theme===mode?"true":"false");
                  });
                }
                apply(cur());
                // Follow the OS setting while in System mode.
                mq.addEventListener("change",function(){if(cur()==="system")apply("system");});
                document.querySelectorAll(".theme-switch").forEach(function(root){
                  var trigger=root.querySelector(".theme-switch-trigger");
                  var menu=root.querySelector(".theme-menu");
                  if(!trigger||!menu)return;
                  function open(o){menu.classList.toggle("theme-menu-hidden",!o);trigger.setAttribute("aria-expanded",o?"true":"false");}
                  trigger.addEventListener("click",function(e){e.stopPropagation();open(menu.classList.contains("theme-menu-hidden"));});
                  menu.querySelectorAll(".theme-option").forEach(function(o){
                    o.addEventListener("click",function(){
                      var m=o.dataset.theme;
                      if(m==="system")localStorage.removeItem("theme");else localStorage.setItem("theme",m);
                      apply(m);open(false);
                    });
                  });
                  document.addEventListener("mousedown",function(e){if(!root.contains(e.target))open(false);});
                  document.addEventListener("keydown",function(e){if(e.key==="Escape")open(false);});
                });
              })();
              var menuBtn=document.getElementById("menu-toggle");
              function setMenu(open){
                document.body.classList.toggle("menu-open",open);
                // Also toggle on <html> so the @media (max-width:767px)
                // overflow-hidden rule (styles.css) can lock background
                // scrolling — matches Nextra's
                // document.documentElement.classList.toggle("x:max-md:overflow-hidden", hasMenu)
                // in nextra-theme-docs/dist/stores/menu.js:10.
                document.documentElement.classList.toggle("menu-open",open);
                menuBtn.setAttribute("aria-expanded",open?"true":"false");
                if(open){
                  // Scroll the current chapter into view inside the
                  // newly-opened sidebar (Nextra parity: sidebar.js:365-374
                  // does the same via scroll-into-view-if-needed).
                  var cur=document.querySelector("#sidebar .sidebar-list li.current");
                  if(cur)cur.scrollIntoView({block:"center",inline:"center"});
                }
              }
              menuBtn.addEventListener("click",function(){
                setMenu(!document.body.classList.contains("menu-open"));
              });
              // Crossing past the mobile breakpoint with the menu still
              // marked open leaves body.menu-open, html.menu-open and
              // aria-expanded="true" stale — CSS already hides the panel,
              // but the a11y tree still reports it as open. Reset state
              // when we leave mobile width. Nextra doesn't do this
              // explicitly, but its Tailwind x:md:hidden + Zustand store
              // mean the visible/state mismatch only surfaces in the
              // hamburger's aria-pressed; mirror that cleanup ourselves.
              matchMedia("(max-width: 767px)").addEventListener("change",function(e){
                if(!e.matches)setMenu(false);
              });
              document.addEventListener("keydown",function(e){
                if(e.key!=="Escape")return;
                // When a search panel is open inside the menu, let
                // search.js's Esc handler close just the panel — closing
                // both at once is jarring. This inline script runs before
                // the deferred search.js module, so bailing here lets
                // search.js still receive the keydown and close the
                // panel (search.js:187-191).
                if(document.querySelector(".search-panel.open"))return;
                setMenu(false);
              });
              // Same-page anchor clicks from the inline TOC inside the
              // mobile menu need to close the menu themselves — otherwise
              // the html.menu-open overflow-hidden rule blocks the native
              // anchor scroll, and the panel stays over the target.
              // Nextra parity: handleClick (sidebar.js:183) on the inline
              // TOC <a> calls setMenu(false).
              document.querySelectorAll(".sidebar-toc a").forEach(function(a){
                a.addEventListener("click",function(){setMenu(false);});
              });
              // Scrollspy: highlight whichever <emu-clause id=…> is
              // currently near the top of the viewport in both the
              // right-rail aside.toc and the inline .sidebar-toc under
              // the current chapter. Mirrors Nextra's
              // heading-anchor.client.js (IntersectionObserver with a
              // top-biased rootMargin: -navbar 0% -80% 0%) feeding the
              // useActiveAnchor store, which <File> reads to apply the
              // active class (sidebar.js:248-258).
              (function(){
                var header=document.querySelector(".site-header");
                var navH=header?header.getBoundingClientRect().height:64;
                // Keep the active entry visible in the right-rail TOC, which
                // scrolls internally: when it lands above/below the list's
                // viewport, nudge only the list's scrollTop (not the page).
                // The 24px margins clear the list's top/bottom fade mask.
                var tocOl=document.querySelector("aside.toc > ol");
                function followToc(a){
                  if(!a||!tocOl)return;
                  var lr=a.getBoundingClientRect(),cr=tocOl.getBoundingClientRect();
                  if(lr.top<cr.top+24)tocOl.scrollTop+=lr.top-cr.top-24;
                  else if(lr.bottom>cr.bottom-24)tocOl.scrollTop+=lr.bottom-cr.bottom+24;
                }
                var io=new IntersectionObserver(function(entries){
                  var hit=entries.find(function(e){return e.isIntersecting;});
                  if(!hit)return;
                  var id=hit.target.id;
                  document.querySelectorAll(".sidebar-toc a.active, aside.toc a.active").forEach(function(a){
                    a.classList.remove("active");
                  });
                  var railActive=null;
                  document.querySelectorAll(".sidebar-toc a[href='#"+id+"'], aside.toc a[href='#"+id+"']").forEach(function(a){
                    a.classList.add("active");
                    if(a.closest("aside.toc"))railActive=a;
                  });
                  followToc(railActive);
                },{rootMargin:"-"+navH+"px 0px -80% 0px"});
                document.querySelectorAll("#content emu-clause[id]").forEach(function(el){
                  io.observe(el);
                });
              })();
              // Sidebar collapse (desktop): single button in the sidebar
              // footer toggles between full (256px) and narrow (60px). When
              // narrow the menu list is hidden and the footer reflows so
              // just the icon-only theme + toggle buttons remain — matches
              // nextra-theme-docs' sidebar.js (x:w-64 ↔ x:w-20 + flex-wrap).
              // The choice is persisted so navigating between pages remembers
              // the user's state.
              var collapseBtn=document.getElementById("sidebar-collapse");
              function setCollapsed(c){
                document.body.classList.toggle("sidebar-collapsed",c);
                collapseBtn.setAttribute("aria-expanded",c?"false":"true");
                collapseBtn.setAttribute("title",c?"Expand sidebar":"Collapse sidebar");
                localStorage.setItem("sidebar",c?"collapsed":"open");
              }
              if(localStorage.getItem("sidebar")==="collapsed")setCollapsed(true);
              collapseBtn.addEventListener("click",function(){
                setCollapsed(!document.body.classList.contains("sidebar-collapsed"));
              });
              // Version switcher dropdown: trigger toggles the menu, outside
              // click + Escape close it. Mirrors the former Nextra
              // version-switcher React component.
              var vsRoot=document.getElementById("version-switcher");
              var vsTrigger=document.getElementById("version-switcher-trigger");
              var vsMenu=document.getElementById("version-switcher-menu");
              function setVsOpen(open){
                vsMenu.classList.toggle("ecma-vs-hidden",!open);
                vsTrigger.setAttribute("aria-expanded",open?"true":"false");
              }
              vsTrigger.addEventListener("click",function(e){
                e.stopPropagation();
                setVsOpen(vsMenu.classList.contains("ecma-vs-hidden"));
              });
              document.addEventListener("mousedown",function(e){
                if(!vsRoot.contains(e.target))setVsOpen(false);
              });
              document.addEventListener("keydown",function(e){
                if(e.key==="Escape")setVsOpen(false);
              });
              // Cmd/Ctrl+K focus on the search input is wired up in
              // search.js (alongside the rest of the search behavior).
              // Show the right kbd hint for the current platform.
              if(/Mac|iPhone|iPad/.test(navigator.platform)){
                document.body.classList.add("is-mac");
              }
              // Variable highlighting: clicking a <var> highlights every
              // same-named <var> within its enclosing clause, cycling 7
              // colours so different variables get different tints; clicking
              // a highlighted var clears them. Direct port of ecmarkup.js's
              // toggleFindLocalReferences (CLAUSE_NODES = clause containers,
              // REFERENCED_CLASSES = referenced0..6).
              (function(){
                var CLAUSE=["EMU-CLAUSE","EMU-INTRO","EMU-ANNEX"];
                var CLASSES=["referenced0","referenced1","referenced2","referenced3","referenced4","referenced5","referenced6"];
                function container(el){
                  var n=el.parentNode;
                  while(n&&CLAUSE.indexOf(n.nodeName)===-1)n=n.parentNode;
                  return n;
                }
                function locals(c,html){
                  var vs=c.querySelectorAll("var"),out=[];
                  for(var i=0;i<vs.length;i++)if(vs[i].innerHTML===html)out.push(vs[i]);
                  return out;
                }
                function chooseIndex(c){
                  var best=0,min=Infinity;
                  for(var i=0;i<CLASSES.length;i++){
                    var n=c.getElementsByClassName(CLASSES[i]).length;
                    if(n<min){min=n;best=i;}
                  }
                  return best;
                }
                document.addEventListener("click",function(e){
                  var v=e.target;
                  if(!v||v.nodeName!=="VAR")return;
                  var c=container(v);
                  if(!c)return;
                  var refs=locals(c,v.innerHTML);
                  if(v.classList.contains("referenced")){
                    refs.forEach(function(el){
                      el.classList.remove("referenced");
                      CLASSES.forEach(function(cl){el.classList.remove(cl);});
                    });
                  }else{
                    var idx=chooseIndex(c);
                    refs.forEach(function(el){el.classList.add("referenced","referenced"+idx);});
                  }
                });
              })();
            `,
          }}
        />
      </body>
    </html>
  );
}
